### ISSUE TITLE
&xc2blade doesn’t give Blade Arts or liked categories

### ISSUE THREAD

**Issue by Renkindle** [ReinaSakuraba/Poppi#1]
Tested the &xc2blade command, was surprised to see nothing for Blade Arts and liked categories of pouch items (not the specific favorite pouch items, those were already there.) Great work on the bot, though!

**Comment by ReinaSakuraba** [comment]
Blade Arts and Favorite Categories will be added within a day. Along with what specials the Blade has.

**Comment by Renkindle** [comment]
Alright, cool! On a side note, somebody I know has Sheba’s Core Crystal in her inventory but isn’t able to pull it, no matter what she tries.
Just gonna close this though since that’s not really relevant to the original issue.

**Comment by ReinaSakuraba** [comment]
You can use the official bot server for further messages. https://discord.gg/jd4P3Ma
